# These are supported funding model platforms
custom: "https://www.patreon.com/HyplexMC/"
#patreon: # Replace with a single Patreon username
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
